"""
ComicVerse Nodes - ComfyUI Custom Nodes for Comic Layout
Comic Assets Library with delete/pending deletion feature
"""

from .comicverse_nodes import (
    NODE_CLASS_MAPPINGS as COMICVERSE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COMICVERSE_DISPLAY_MAPPINGS,
)
from .prompt_loader_node import (
    NODE_CLASS_MAPPINGS as PROMPT_LOADER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_LOADER_DISPLAY_MAPPINGS,
)
from .prompt_rolling_node import (
    NODE_CLASS_MAPPINGS as PROMPT_ROLLING_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_ROLLING_DISPLAY_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **COMICVERSE_CLASS_MAPPINGS,
    **PROMPT_LOADER_CLASS_MAPPINGS,
    **PROMPT_ROLLING_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **COMICVERSE_DISPLAY_MAPPINGS,
    **PROMPT_LOADER_DISPLAY_MAPPINGS,
    **PROMPT_ROLLING_DISPLAY_MAPPINGS,
}

WEB_DIRECTORY = "./js"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
