"""
ComicVerse Nodes - ComfyUI Custom Nodes for Comic Layout
Comic Assets Library with delete/pending deletion feature
Prompt Library Loader and Rolling with Text Preview
Library Manager for editing prompt libraries
"""

# Import API routes first to register them with PromptServer
from . import library_manager_api

from .comicverse_nodes import (
    NODE_CLASS_MAPPINGS as COMICVERSE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COMICVERSE_DISPLAY_MAPPINGS,
)
from .prompt_loader_node import (
    NODE_CLASS_MAPPINGS as PROMPT_LOADER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_LOADER_DISPLAY_MAPPINGS,
)
from .prompt_rolling_node import (
    NODE_CLASS_MAPPINGS as PROMPT_ROLLING_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_ROLLING_DISPLAY_MAPPINGS,
)
from .prompt_queue_node import (
    NODE_CLASS_MAPPINGS as PROMPT_QUEUE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_QUEUE_DISPLAY_MAPPINGS,
)
from .text_preview_node import (
    NODE_CLASS_MAPPINGS as TEXT_PREVIEW_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_PREVIEW_DISPLAY_MAPPINGS,
)
from .library_manager_node import (
    NODE_CLASS_MAPPINGS as LIBRARY_MANAGER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LIBRARY_MANAGER_DISPLAY_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **COMICVERSE_CLASS_MAPPINGS,
    **PROMPT_LOADER_CLASS_MAPPINGS,
    **PROMPT_ROLLING_CLASS_MAPPINGS,
    **PROMPT_QUEUE_CLASS_MAPPINGS,
    **TEXT_PREVIEW_CLASS_MAPPINGS,
    **LIBRARY_MANAGER_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **COMICVERSE_DISPLAY_MAPPINGS,
    **PROMPT_LOADER_DISPLAY_MAPPINGS,
    **PROMPT_ROLLING_DISPLAY_MAPPINGS,
    **PROMPT_QUEUE_DISPLAY_MAPPINGS,
    **TEXT_PREVIEW_DISPLAY_MAPPINGS,
    **LIBRARY_MANAGER_DISPLAY_MAPPINGS,
}

WEB_DIRECTORY = "./js"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
